name: Test

on:
  push:
    branches:
    - main
    paths-ignore:
      - "*.md"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: "pip" # caching pip dependencies

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest

      - name: Run tests
        shell: bash
        run: |
          python -m pytest tests
